# Generated by Django 2.2 on 2019-04-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Marker',
        ),
    ]
