# Generated by Django 2.2 on 2019-04-23 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_auto_20190423_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
